# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: "14"
    - run: npm install
    - run: npm run build --if-present
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      if: ${{ success() }}
      with:
          name: dist
          path: dist

    - uses: actions/checkout@v2
    - name: download
      uses: actions/download-artifact@v2
      if: ${{ success() }}
      with:
        # Artifact name
        name: dist
        
    - name: Deploy
      uses: tibor19/static-website-deploy@v1
      if: ${{ success() }}
      with:
          # Connection String of the Azure Storage Container
          connection-string: ${{ secrets.CONNECTION_STRING }}
          # Folder containing the files to be uploaded to the Storage Container
          folder: "dist"
          # Enabled static website
          enabled-static-website: true
          # If the existing files should be removed before uploading the new files
          remove-existing-files: true
